openapi: 3.0.0
info:
  title: LGBTQ Social Media API List
  description: This is a reference api list of a LGBTQ Social Media Backend.
  version: 1.0.0
  contact:
    email: ankuragarwa246@gmail.com
servers:
  - url: /
    description: Production Server
  - url: http://localhost:9999/api
    description: Development server